name: Publish

on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      contents: write
    steps:
      - name: Check out
        uses: actions/checkout@v4

      - name: Install Emacs
        run: sudo apt install emacs-nox --yes

      - name: Examine file permissions
        run: ls -ld .

      - name: Examine file tree
        run: ls -lR site-publisher

      - name: Build the site
        # run: ./publi.sh
        run: (cd site-publisher && emacs -Q --script build-site.el)

      - name: Publish generated content to GitHub Pages
        uses: JamesIves/github-pages-deploy-action@v4
        with:
          folder: site-publisher/public
          branch: gh-pages
          single-commit: true
